### Get word game API 
GET http://localhost:1205/api/word_game?sentence=My%20name%20is%20Amukelani%20Mthombeni%20Wiseman%20,%20what%20is%20yours
Content-Type: application/json

### GET total phone bill API
POST  http://localhost:1205/api/phonebill/total?usage=call,%20sms,%20sms,%20call,%20sms,%20call,%20,%20call,%20call,%20sms
Content-Type: application/json


###  total data bill API
GET http://localhost:1205/api/phonebill/callPrice?usage=call,%20sms,%20sms,%20call,%20sms,%20call,%20,%20call,%20call,%20sms
Content-Type: application/json



### GET total call bill API
GET http://localhost:1205/api/phonebill/dataPrice?usage=call,%20sms,%20sms,%20call,%20sms,%20data,%20,%20call,%20call,%20sms
Content-Type: application/json


### GET total sms bill API
GET http://localhost:1205/api/phonebill/smsPrice?usage=call,%20sms,%20sms,%20call,%20sms,%20call,%20,%20call,%20call,%20sms
Content-Type: application/json

### GET enough airtime API
POST  http://localhost:1205/api/enoughAirtime?usage=call,%20sms,%20sms,%20call,%20sms,%20call,%20,%20call,%20call,%20sms&result=50
Content-Type: application/json


